
server:
  port: 8070
spring:
  application:
    name: ems
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee-management
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
